proxies:
  - name: "tuic-bitterzhou"
    type: tuic
    server: 198.46.145.251
    port: 7777
    uuid: 5d6747ae-aaeb-4396-9bcb-769ebe4c9df2
    password: 5d6747ae-aaeb-4396-9bcb-769ebe4c9df2
    ip: 198.46.145.251
    heartbeat-interval: 10000
    alpn: ["h3"]
    reduce-rtt: true
    request-timeout: 8000
    udp-relay-mode: native
    congestion-controller: bbr
    skip-cert-verify: true
    sni: www.bing.com

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - "tuic-bitterzhou"

rules:
  - MATCH,DIRECT
