port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090

proxies:
  - name: "tuic-bitterzhou"
    type: tuic
    server: 198.46.145.251
    port: 7777
    uuid: 5d6747ae-aaeb-4396-9bcb-769ebe4c9df2
    password: 5d6747ae-aaeb-4396-9bcb-769ebe4c9df2
    ip: 198.46.145.251
    heartbeat-interval: 10000
    alpn: ["h3"]
    reduce-rtt: true
    request-timeout: 8000
    udp-relay-mode: native
    congestion-controller: bbr
    skip-cert-verify: true
    sni: www.bing.com

proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - "tuic-bitterzhou"
      - DIRECT

  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 50
    proxies:
      - "tuic-bitterzhou"

rules:
  - DOMAIN-SUFFIX,github.com,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-KEYWORD,google,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN-KEYWORD,youtube,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - GEOIP,CN,DIRECT
  - MATCH,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
